import { useEffect, useRef, useState } from "react";
import { X } from "lucide-react";
import type { StickerPack } from "@/shared/types";

export function StickerStudio({ packs, onClose, onSave }: { packs: StickerPack[]; onClose: () => void; onSave: (file: File, packId: string, tags: string[]) => Promise<void> }) {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [packId, setPackId] = useState(packs[0]?.id ?? ""); const [tags, setTags] = useState("😀"); const [busy, setBusy] = useState(false);
  useEffect(() => () => { if (file) URL.revokeObjectURL(URL.createObjectURL(file)); }, [file]);
  const choose = (candidate: File | undefined) => { if (candidate && ["image/png", "image/webp", "image/jpeg"].includes(candidate.type) && candidate.size <= 10 * 1024 * 1024) setFile(candidate); };
  return <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-6" role="dialog" aria-modal="true" aria-label="Sticker Studio"><div className="w-[760px] max-w-full rounded-xl bg-card p-5 shadow-xl">
    <div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Sticker Studio</h2><button aria-label="Close" onClick={onClose}><X className="h-5 w-5" /></button></div>
    <div className="mt-5 grid grid-cols-[1fr_240px] gap-6"><div onDragOver={e => e.preventDefault()} onDrop={e => { e.preventDefault(); choose(e.dataTransfer.files[0]); }} className="flex h-[512px] items-center justify-center rounded-lg border border-dashed border-border bg-[linear-gradient(45deg,#eee_25%,transparent_25%),linear-gradient(-45deg,#eee_25%,transparent_25%),linear-gradient(45deg,transparent_75%,#eee_75%),linear-gradient(-45deg,transparent_75%,#eee_75%)] bg-[length:24px_24px] bg-[position:0_0,0_12px,12px_-12px,-12px_0px]"><button className="rounded-md bg-primary px-4 py-2 text-primary-foreground" onClick={() => input.current?.click()}>{file ? file.name : "Choose or drop image"}</button><input ref={input} type="file" hidden accept="image/png,image/webp,image/jpeg" onChange={e => choose(e.target.files?.[0])} /></div><div className="space-y-4"><label className="block text-sm">Owned pack<select className="mt-1 w-full rounded border bg-transparent p-2" value={packId} onChange={e => setPackId(e.target.value)}>{packs.map(p => <option key={p.id} value={p.id}>{p.title}</option>)}</select></label><label className="block text-sm">Emoji tags<input className="mt-1 w-full rounded border bg-transparent p-2" value={tags} onChange={e => setTags(e.target.value)} /></label><button disabled={!file || !packId || busy} className="w-full rounded bg-primary px-3 py-2 text-primary-foreground disabled:opacity-50" onClick={async () => { if (!file) return; setBusy(true); try { await onSave(file, packId, tags.trim().split(/\s+/).filter(Boolean)); onClose(); } finally { setBusy(false); } }}>Save and send</button></div></div>
  </div></div>;
}
