import { useId, useState } from "react";
import { Dialog } from "@/shared/components/Dialog";
import { Button } from "@/shared/components/Button";
import { broadcastChannelsApi } from "@/api/broadcastChannels";
import { useAppStore } from "@/store";
import { isReservedBroadcastRootName } from "../rootNames";

export function CreateBroadcastChannelModal({ onClose }: { onClose: () => void }) {
  const titleId = useId(); const setChannel = useAppStore((s) => s.setBroadcastChannel); const setActiveChat = useAppStore((s) => s.setActiveChat);
  const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [username, setUsername] = useState(""); const [visibility, setVisibility] = useState<"public" | "private">("public"); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setError(""); if (visibility === "public" && isReservedBroadcastRootName(username)) { setError("That username is reserved by the application."); return; } setBusy(true); try { const channel = await broadcastChannelsApi.create({ display_name: name, description: description || null, visibility, ...(visibility === "public" ? { username } : {}) }); setChannel(channel); window.history.replaceState(null, "", `#/broadcast/${channel.public_id}`); setActiveChat(null); onClose(); } catch { setError("Channel could not be created."); } finally { setBusy(false); } }
  return <Dialog open onClose={onClose} labelledBy={titleId} className="w-full max-w-md"><form onSubmit={submit} className="space-y-4 p-5"><h2 id={titleId} className="text-lg font-semibold">Create broadcast channel</h2><label className="block text-sm">Display name<input required value={name} onChange={(e) => setName(e.target.value)} className="mt-1 w-full rounded border border-border bg-background p-2" /></label><label className="block text-sm">Description<textarea value={description} onChange={(e) => setDescription(e.target.value)} maxLength={500} className="mt-1 w-full rounded border border-border bg-background p-2" /></label><label className="block text-sm">Visibility<select value={visibility} onChange={(e) => setVisibility(e.target.value as "public" | "private")} className="mt-1 w-full rounded border border-border bg-background p-2"><option value="public">Public</option><option value="private">Private</option></select></label>{visibility === "public" && <label className="block text-sm">Username<input required minLength={5} pattern="[a-z0-9_]+" value={username} onChange={(e) => setUsername(e.target.value)} placeholder="news_channel" className="mt-1 w-full rounded border border-border bg-background p-2" /></label>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={onClose}>Cancel</Button><Button type="submit" disabled={busy}>{busy ? "Creating…" : "Create"}</Button></div></form></Dialog>;
}
